kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  namespace: dev
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-3-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: nexus-3-claim
    namespace: dev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubework1
          

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-3-claim
  namespace: dev
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
