---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30881
    name: nexus3
  selector:
    app: nexus3
